apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eduk8s

resources:
- crds-v1/workshop.yaml
- crds-v1/workshop-environment.yaml
- crds-v1/workshop-session.yaml
- crds-v1/workshop-request.yaml
- crds-v1/training-portal.yaml
- crds-v1/system-profile.yaml
- operator/namespace.yaml
- operator/clusterrole.yaml
- operator/serviceaccount.yaml
- operator/rolebinding.yaml
- operator/deployment.yaml

configMapGenerator:
- name: eduk8s-images
  env: image-mappings.env
